spring:
  security:
    oauth2:
      client:
        registration:
         google:
          clientId: 
          clientSecret: 
          scope:
           - email
           - profile
server:
   port: 13000